version: 2

models:
  - name: staging.customers
    columns:
      - name: customer_id
        data_tests:
          - unique
          - not_null

  - name: staging.orders
    columns:
      - name: order_id
        data_tests:
          - unique
          - not_null
      - name: status
        data_tests:
          - accepted_values:
              values:
                ["placed", "shipped", "completed", "return_pending", "returned"]

  - name: staging.payments
    columns:
      - name: payment_id
        data_tests:
          - unique
          - not_null
      - name: payment_method
        data_tests:
          - accepted_values:
              values: ["credit_card", "coupon", "bank_transfer", "gift_card"]
